### ISSUE TITLE
0.2 release plan

### ISSUE THREAD

**Issue by PVince81** [owncloud/pyocclient#115]
#### Issues
- [x] share API missing functions: https://github.com/owncloud/pyocclient/issues/7#issuecomment-50883124 https://github.com/owncloud/pyocclient/pull/69
- [x] provisioning API completeness (check whether we have everything)
    - [x] add/edit_user https://github.com/owncloud/pyocclient/issues/86
    - [x] unit tests for all new provisioning API functions: https://github.com/owncloud/pyocclient/issues/77
- [ ] other milestone issues: https://github.com/owncloud/pyocclient/milestones/0.2

#### Release
- [x] update changelog
- [x] update authors
- [x] update version in setup.py, docs, etc
- [x] tag milestone
- [x] build egg and upload to pypi
- [x] announce

**Comment by PVince81** [comment]
Should probably release a 0.2~RC1 for testing first.

**Comment by PVince81** [comment]
Just read this https://www.python.org/dev/peps/pep-0440/#pre-releases, seems the format for RC version would be: 0.2rc1

**Comment by PVince81** [comment]
Some progress regarding authors: https://github.com/owncloud/pyocclient/pull/162

**Comment by PVince81** [comment]
Ok, I messed up with the RC1, not knowing whether to use "sdist" or "bdist_egg".
I redid the 0.2rc2 PiPy package with bdist_egg as rc2.

- [ ] After testing, redo a release with 0.2 (final)
